language: node_js
cache: npm
notifications:
  email: false
node_js:
  - 12
  - node
install: npm install
script:
  - npm ls typescript
  - npm ls dtslint
  - npm ls kcd-scripts
  - npm run validate
  - npx codecov@3
branches:
  only:
    - master
    - debug-ts-transition

jobs:
  include:
    - stage: release
      node_js: 14
      script: kcd-scripts travis-release
      if: fork = false
